import type { Metadata } from "next";
import "../globals.css";
import localFont from "next/font/local";
import clsx from "clsx";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
export const metadata: Metadata = {
  title: "Orimi - Lead you to excellence",
  description: "Generated by create next app",
};

const neue = localFont({
  src: [
    {
      path: "../../../public/fonts/ppneuemontreal-thin.otf",
      weight: "300",
    },
    {
      path: "../../../public/fonts/ppneuemontreal-book.otf",
      weight: "400",
    },
    {
      path: "../../../public/fonts/ppneuemontreal-medium.otf",
      weight: "500",
    },
    {
      path: "../../../public/fonts/ppneuemontreal-bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-neuemontreal",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(`${neue.variable} font-neuemontreal`)}>
        <Analytics />
        <SpeedInsights />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
